version: '3.7'
services:
  # Application

  umbriel-api:
    image: umbriel-dashboard
    container_name: umbriel-dashboard
    restart: always
    ports:
      - ${APP_PORT}:3000
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
